
title: Git Makralkaza IT Support on the Hub!
description: Jackson, TN SMB IT compliance tips, Microsoft 365 automation, and templates.
url: ""
baseurl: ""
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
